### ISSUE TITLE
Combination of STdeconvolve with BayesSpace

### ISSUE THREAD

**Issue by Acaro12** [JEFworks-Lab/STdeconvolve#23]
Hi bmill3r,

Thank you very much for this exciting package. It is very useful, especially when retrospectively analyzing archival tissue with Visium FFPE.

Since you feature the BayesSpace package in the Nat Com Paper (https://github.com/edward130603/BayesSpace), I was wondering if an upstream BayesSpace resolution enhancement would improve the performance of the STdeconvolve algorithm. I could imagine that STdeconvolve would in principle benefit from a higher (although predicted) resolution of the underlying gene expression matrix. 

Do you think that this approach would be statistically sound or would it violate the underlying STdeconvolve assumptions? 

Thank you very much for time in advance and thanks again for your great work.

**Comment by bmill3r** [comment]
Hi @Acaro12,

Thanks so much for the idea! I think in principle `STdeconvolve` would benefit from a higher resolution gene expression matrix, which could be provided by `BayesSpace`. However, the comparison between `STdeconvolve` and `BayesSpace` performed in the paper was to demonstrate that one of the assumptions made by `BayesSpace`, that spatially adjacent spots are correlated in terms of their transcriptional profiles, isn't necessarily true in all cases. Specifically, we looked at the thymus region of a mouse brain coronal section, which has high cell type heterogeneity, and found that this assumption led to worse predictions by `BayesSpace`. This was likely because `BayesSpace` uses spatially adjacent spots to determine the predicted transcriptional profiles of sub-spots. In cases like the thymus, where adjacent spots may actually contain different cell types, this assumption leads to incorrect transcriptional profile predictions. Now, I do think that in many cases the same cell types can be expected in adjacent spots and so the assumptions that `BayesSpace` makes are probably reasonable. But in situations where the underlying biology does not support this, `BayesSpace` may predict incorrect transcriptional profiles, which in turn would lead to less accurate predictions by `STdeconvolve`. Note that `STdeconvolve` currently treats each spot independently and does not take into account spatially adjacent spot information during the deconvolution.

Hope this helps and please let me know if you have any other questions,
Brendan

**Comment by Acaro12** [comment]
Dear Brendan,

Thank you so much for your detailed reply and sorry for the late reresponse. 
I know decided to use both methods independently from another and used the corrMatrix to compare their output. The conclusions I derive from them in my specific project seem to support each other, although, as expected they are both informative in their way.

Thanks again.
I will open another issue not related to this one here.
Best,
Christoph
