### ISSUE TITLE
dependency 'liger' is not available

### ISSUE THREAD

**Issue by LX2006** [JEFworks-Lab/STdeconvolve#59]
Just a heads-up that the package ‘liger’ was removed from the CRAN repository on 2024-06-14. As a result, you will encounter an error message stating that the dependency 'liger' is not available for the package 'STdeconvolve'.

A temporary workaround is to install ‘liger’ from the CRAN archive before installing ‘STdeconvolve’ :

`install.packages("https://cran.r-project.org/src/contrib/Archive/liger/liger_2.0.1.tar.gz", repos = NULL, type = "source")`

It would be great to fix this issue permanently.

**Comment by JEFworks** [comment]
Thanks for the heads up!

Since LIGER is on Github (https://github.com/JEFworks/liger), my sense is that using `remotes` will provide a more permanent solution: https://remotes.r-lib.org/articles/dependencies.html

So the `DESCRIPTION` file can be updated to remove `liger` from the `Imports:` list and instead add `Remotes: JEFworks/liger`

**Comment by JEFworks** [comment]
Closing as this should be resolved in commit 380d134da0d78c0b439ed532aecee0f1aab1ab11
